### PR TITLE
Update API url in SunlightOpenStates.php

### PR DESCRIPTION
**Pull request by evanhsu**
Changed from `http://...` to `https://...`

### CODE REVIEW

**Comment by lobostome** [comment]
Thanks for the PR. The docs still indicate http as the protocol. Is there a change to that?

> All API calls are URLs in the form http://openstates.org/api/v1/METHOD/

**Source**: http://sunlightlabs.github.io/openstates-api/index.html

**Comment by evanhsu** [comment]
It looks like they must have forgotten to update their docs - attempting to
access the Open States API using the http protocol results in a 301 MOVED
PERMANENTLY.  The URL works when used with the HTTPS protocol, however.

**Comment by evanhsu** [comment]
Thanks for merging!
Would you mind tagging a new release as well, please?

**Comment by lobostome** [comment]
The release has been tagged. I will add some automation around integration and release once I get some free time.

Thanks for the support.

**Pull request merged**
